Adding Directlake options for collecting metrics
sql-bi/VertiPaq-Analyzer pull request #118
Opened 2024-03-20 23:32 UTC by dgosbell

Added 3 different modes for direct lake models so that we do not always force all columns to be transcoded into memory.

* **ResidentOnly** - only run the distinctcount queries on columns that are current resident in memory
* **Referenced** - run distinctcount queries on columns that are referenced by measures or relationships. This should provide the minimum information required for performance analysis of measures and for tools like DAX Optimizer.
* **Full** - run distinctcount queries on all columns

I've added this option since the default behaviour at the moment is the same as **Full** and this can be detrimental to large models. It can take longer than necessary and potentially may still not produce the desired result since as we cycle through all the columns it could force some of the earlier columns to be paged out of memory.

I've set **ResidentOnly** as the default as it's the cheapest/fastest option.

Note that if an option other than **ResidentOnly** is chosen I am re-running the DMV collection after the stats collection has been run since the memory usage is usually changed as a result of running the distinctcount queries.

I did consider whether to add the selected Direct Lake analysis mode as a property to the vpax file, but I decided against his for the time being since it can be implied by checking the IsResident property on a column.

2024-03-21 12:00 UTC, albertospelta requested changes

2024-03-21 12:10 UTC, albertospelta commented on src/Dax.Model.Extractor/StatExtractor.cs
> +                    // we are analyzing DQ and both columns are in a table with DQ partitions
@dgosbell is the DQ analysis enabled if either column is in a table with DQ partitions? Just for my understanding. Thanks!

2024-03-21 21:54 UTC, dgosbell commented on src/Dax.Model.Extractor/StatExtractor.cs
> +                    // we are analyzing DQ and both columns are in a table with DQ partitions
Thanks for catching that. You are correct it is checking if **either** column is in a table with DQ partitions

2024-03-22 07:58 UTC, albertospelta approved these changes

2024-03-22 07:58 UTC, merged